sudo: true
services:
  - docker
dist: trusty

env:
  - DOCKER_IMAGE=travis-odp-lng-ubuntu_16.04 IMGDIR=ubuntu_16.04
  - DOCKER_IMAGE=travis-odp-lng-ubuntu_18.04 IMGDIR=ubuntu_18.04

script:
  - docker build -t "$DOCKER_IMAGE" "$IMGDIR"
